<a href="https://colab.research.google.com/github/llayer/inferno/blob/master/inferno_TF1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#INFERNO with TF 1.x

In [1]:
!pip install tensorflow==1.10.1

     |████████████████████████████████| 58.4MB 74kB/s 
     |████████████████████████████████| 573kB 43.4MB/s 
     |████████████████████████████████| 3.3MB 43.0MB/s 
     |████████████████████████████████| 12.2MB 50.1MB/s 
ERROR: xarray 0.15.1 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: xarray 0.15.1 has requirement setuptools>=41.2, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: spacy 2.2.4 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: plotnine 0.6.0 has requirement numpy>=1.16.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: imgaug 0.2.9 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: google-auth 1.7.2 has requirement setuptools>=40.3.0, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: fastai 1.0.60 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: datascience 0.10.6 has re

In [2]:
!pip install tensorflow-probability==0.3.0

     |████████████████████████████████| 512kB 2.9MB/s 
  Found existing installation: tensorflow-probability 0.9.0
    Uninstalling tensorflow-probability-0.9.0:
      Successfully uninstalled tensorflow-probability-0.9.0


In [0]:
from tqdm import trange

In [4]:
import tensorflow as tf
import tensorflow_probability as tfp

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

In [0]:
ge = tf.contrib.graph_editor
ds = tfp.distributions

In [6]:
!pip install git+https://github.com/pablodecm/neyman.git

  Cloning https://github.com/pablodecm/neyman.git to /tmp/pip-req-build-tfu6xjlk
  Running command git clone -q https://github.com/pablodecm/neyman.git /tmp/pip-req-build-tfu6xjlk
     |████████████████████████████████| 71kB 2.2MB/s 
  Created wheel for neyman: filename=neyman-0.0.1-cp36-none-any.whl size=5293 sha256=7ccfb28ff2268b8c4f4756f61dea20ef750c5e10129b98717d0542a2a9a158ed
  Stored in directory: /tmp/pip-ephem-wheel-cache-z244rwd7/wheels/c5/02/c3/daef8b8e644e4dbee14ad489db8f51c08838dfcc1a621ed3ea
  Created wheel for edward: filename=edward-1.3.5-cp36-none-any.whl size=90388 sha256=c3120050457dcc1540f7bea299502807a751d27bb1f05061322f04c2936dbc1c
  Stored in directory: /root/.cache/pip/wheels/ae/61/0c/1f36f3f0c629d1b7a24d042d2c37015a66c091729c95dd8425
Successfully built neyman edward


/usr/local/lib/python3.6/dist-packages/google/colab/_pip.py:89: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/lib/python3.6/dist-packages/edward-1.3.5.dist-info/top_level.txt' mode='r' encoding='UTF-8'>
  for line in open(toplevel):
/usr/local/lib/python3.6/dist-packages/google/colab/_pip.py:89: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/lib/python3.6/dist-packages/neyman-0.0.1.dist-info/top_level.txt' mode='r' encoding='UTF-8'>
  for line in open(toplevel):


In [7]:
!ls

sample_data


In [0]:
from neyman.inferences import batch_hessian

In [9]:
! git clone https://github.com/llayer/paper-inferno

Cloning into 'paper-inferno'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 1063 (delta 8), reused 7 (delta 0), pack-reused 1048
Receiving objects: 100% (1063/1063), 1.56 MiB | 20.44 MiB/s, done.
Resolving deltas: 100% (687/687), done.


In [10]:
%cd paper-inferno/

/content/paper-inferno


In [11]:
!ls

code  environment.yml  LICENSE	notebooks  paper  README.md  setup.cfg


In [12]:
%cd code

/content/paper-inferno/code


In [13]:
!ls

benchmarking.py		       synthetic_3D_inferno.py
extended_model.py	       synthetic_3D_train_cross_entropy.py
fisher_matrix.py	       synthetic_3D_train_inferno.py
summary_statistic_computer.py  template_likelihood.py
synthetic_3D_cross_entropy.py  template_model.py
synthetic_3D_example.py        train_helpers.py


In [0]:
from neyman.inferences import batch_hessian

from synthetic_3D_example import SyntheticThreeDimExample
from train_helpers import MixtureBatcher
import os
import json
import itertools as it
from fisher_matrix import FisherMatrix
import numpy as np

In [0]:
k = tf.keras
ds = tfp.distributions
ge = tf.contrib.graph_editor

In [0]:
class SyntheticThreeDimInferno(object):

  def __init__(self, model_path, poi, pars, seed, aux={}):

    tf.set_random_seed(seed)

    self.problem = SyntheticThreeDimExample()

    self.batcher = MixtureBatcher(["sig", "bkg"])

    s_batch = self.batcher.batch["sig"]
    b_batch = self.problem.transform_bkg(self.batcher.batch["bkg"])
    b_sizes = [tf.shape(s_batch)[0], tf.shape(b_batch)[0]]
    train_batch = tf.concat([s_batch, b_batch], axis=0,
                            name="input_batch")

    k_init = "he_normal"
    Dense = k.layers.Dense
    self.nn_model = k.Sequential([Dense(units=100, activation="relu",
                                        kernel_initializer=k_init,
                                        input_shape=(3,)),
                                  Dense(units=100, activation="relu",
                                        kernel_initializer=k_init),
                                  Dense(units=10, activation="linear")])

    self.logits = self.nn_model(train_batch)
    self.temperature = tf.placeholder_with_default(1., shape=())
    self.probs = tf.nn.softmax(self.logits / self.temperature)

    s_probs, b_probs = tf.split(self.probs, b_sizes, axis=0)

    s_counts = tf.reduce_mean(s_probs, axis=0)
    b_counts = tf.reduce_mean(b_probs, axis=0),

    self.exp_counts = tf.cast(self.problem.s_exp * s_counts +
                              self.problem.b_exp * b_counts,
                              dtype=tf.float64)

    self.pois = ds.Poisson(self.exp_counts, name="poisson")
    self.asimov = tf.stop_gradient(self.exp_counts, name="asimov")

    self.nll = - tf.cast(tf.reduce_sum(self.pois.log_prob(self.asimov)),
                         name="nll", dtype=tf.float32)

    all_pars = list(self.problem.all_pars.values())
    self.hess_nll, self.grad_nll = batch_hessian(self.nll,
                                                 all_pars)

    self.aux = aux

    self.nll_aux = {}
    self.hess_nll_aux = {}
    for par, dist in self.aux.items():
        self.nll_aux[par] = -dist.log_prob(self.problem.all_pars[par])
        self.hess_nll_aux[par], _ = batch_hessian(self.nll_aux[par],
                                                  all_pars)

    self.ext_nll = sum([self.hess_nll] + list(self.hess_nll_aux.values()))

    self.cov_nll = self.cov_matrix(pars)
    idx_poi = pars.index(poi)
    self.loss = self.cov_nll[idx_poi, idx_poi]

    # remove stop gradient after loss is computed
    ge.edit.bypass(self.asimov.op)

    self.lr = tf.placeholder(shape=(), dtype=tf.float32)
    self.optimizer = tf.train.GradientDescentOptimizer(self.lr)
    self.global_step = tf.Variable(0, name='global_step', trainable=False)
    self.train_op = self.optimizer.minimize(
        self.loss, global_step=self.global_step)

    self.init_op = tf.global_variables_initializer()

    self.model_path = model_path

    if not os.path.exists(self.model_path):
      os.makedirs(self.model_path)

    json_str = self.nn_model.to_json()
    with open(f'{self.model_path}/model.json', 'w') as f:
      json.dump(json_str, f)

    self.saver = tf.train.Saver()
    self.history = {}

  def cov_matrix(self, pars):

    pars = tuple(pars)

    indices = [list(self.problem.all_pars.keys()).index(par) for par in pars]
    idx_subset = np.reshape(list(it.product(indices, indices)),
                            (len(pars), len(pars), -1))
    hess_subset = tf.gather_nd(self.ext_nll, idx_subset)
    cov_nll = tf.matrix_inverse(hess_subset)

    return cov_nll

  def fit(self, n_epochs, lr, temperature, batch_size, seed, par_phs={}):

    with tf.Session() as sess:
      train_arrays = sess.run(self.problem.train_data())
      valid_arrays = sess.run(self.problem.valid_data())

    phs_train = {self.lr: lr,
                 self.temperature: temperature}

    phs_val = {self.temperature: temperature}

    rs = np.random.RandomState(seed=seed)

    with tf.Session() as sess:

      #writer = tf.summary.FileWriter('logs', sess.graph)

      k.backend.set_session(sess)
      sess.run(self.init_op)
      batch_n = 0
      with trange(n_epochs) as t:
        for i in t:
          shuffle_seed = rs.randint(np.iinfo(np.int32).max)
          self.batcher.init_iterator(train_arrays,
                                     batch_size=batch_size, seed=shuffle_seed)
          while True:
            try:
              batch_n += 1

              
              loss_t, _ = sess.run([self.loss, self.train_op], phs_train)
              print( loss_t )
              print( self.loss.eval() )

              """
              loss_t = sess.run(self.loss, phs_train)
              print( "Loss in first session run" )
              print(self.loss.eval())
              print( "Cov first session run" )
              print(self.cov_nll.eval())
              sess.run(self.train_op, phs_train)
              print( "Loss in second session run" )
              print(self.loss.eval())
              print( "Cov second session run" )
              print(self.cov_nll.eval())
              """
              self.history.setdefault("loss_train", []).append(
                  [batch_n, float(np.sqrt(loss_t))])
            except tf.errors.OutOfRangeError:
              break
          # fix seed for validation set (no need to shuffle)
          self.batcher.init_iterator(valid_arrays,
                                     batch_size=batch_size, seed=20)
          val_losses = []
          while True:
            try:
              loss_t = sess.run([self.loss], phs_val)
              val_losses.append(np.sqrt(loss_t))
            except tf.errors.OutOfRangeError:
              break
          val_loss = np.mean(val_losses)
          val_loss_std = np.std(val_losses, ddof=1)
          t.set_postfix({"mean_val_loss": val_loss})
          self.history.setdefault("loss_valid", []).append(
              [batch_n, float(val_loss)])
          self.history.setdefault("loss_std_valid", []).append(
              [batch_n, float(val_loss_std)])

      self.nn_model.save_weights(f'{self.model_path}/model.h5')
      self.saver.save(sess, f'{self.model_path}/model.ckpt',
                      global_step=self.global_step)
      with open(f'{self.model_path}/history.json', 'w') as fp:
        json.dump(self.history, fp)

  def load_weights(self):
    sess = tf.get_default_session()
    last_ckpt = tf.train.latest_checkpoint(f'{self.model_path}')
    print("loading_vars_from", last_ckpt)
    self.saver.restore(sess, last_ckpt)

  def eval_hessian(self, temperature):

    phs_val = {self.temperature: temperature}

    with tf.Session() as sess:
      valid_arrays = sess.run(self.problem.valid_data())
      self.load_weights()
      self.batcher.init_iterator(valid_arrays,
                                 batch_size=-1, seed=20)
      hess, hess_aux = sess.run([self.hess_nll, self.hess_nll_aux], phs_val)
      print(hess)


    pars = list(self.problem.all_pars.keys())
    fisher = FisherMatrix(hess, pars)
    aux_fisher = FisherMatrix(sum(hess_aux.values()), pars)

    return fisher, aux_fisher

In [25]:
n_epochs = 5
lr = 1e-6
batch_size = 1000
t_train = 0.1
t_eval = 0.05

n_inits = 100
seed = 7

pars = ["s_exp", "r_dist", "b_rate"]

aux = {"r_dist": ds.Normal(loc=2.0, scale=0.4),
       "b_rate": ds.Normal(loc=3.0, scale=1.)}


inf_path = f"inf_ne_{n_epochs}_lr_{lr}_bs_{batch_size}_t_{t_train}"

inferno = SyntheticThreeDimInferno(model_path=inf_path, poi="s_exp",
                                    pars=pars, seed=seed, aux=aux)

inferno.fit(n_epochs=n_epochs, lr=lr, batch_size=batch_size,
            temperature=t_train, seed=seed)

inf_fisher, inf_aux_fisher = inferno.eval_hessian(temperature=t_eval)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:536: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  append_fn(tensor_proto, proto_values)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:536: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  append_fn(tensor_proto, proto_values)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:536: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  append_fn(tensor_proto, proto_values)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:536: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  append_fn(tensor_proto, proto_values)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:536: DeprecationWarning: np.asscalar(a) is deprecated 

840.94995
882.85925
884.2228
854.3461
851.02435
864.0018
816.5241
811.79376
715.1856
837.3792
687.2085
854.9623
823.84546
861.7039
779.91895
846.92084
645.08887
817.533
718.5205
837.9859
789.7924
830.7519
786.24713
805.4109
766.00305
815.4682
702.5723
824.15314
663.26434
781.40894
733.53796
843.4815
784.0845
819.2976
715.77673
816.9187
678.92523
830.67267
701.0779
776.1544
761.05145
840.65717
664.36597
842.1871
700.8301
826.0392
775.78735
808.75543
788.26306
778.8504
631.689
797.07074
701.0061
819.16284
732.91705
811.4951
748.68805
843.276
828.1642
826.07434
692.283
826.7926
793.3572
821.2981
647.0918
836.2655
576.26733
833.21545
720.9707
820.2175
725.1554
851.19385
627.8682
812.8677
803.03876
794.16394
630.6521
800.01874
730.9766
800.96765
591.69464
801.944
608.8696
812.1859
700.0051
821.1863
673.2455
847.32697
668.03564
839.87146
773.226
817.23865
613.7815
822.8358
567.7438
807.341
723.9433
812.798
776.7808
828.9555


 20%|██        | 1/5 [00:15<01:02, 15.53s/it, mean_val_loss=26.3]

640.9411
821.6849
729.2724
789.4684
682.7132
832.25916
770.3797
844.37024
634.43304
822.67065
652.86664
803.5826
555.7286
828.3774
657.6948
825.6535
661.98065
803.8457
689.6128
805.90216
570.515
793.208
687.77325
794.2541
716.331
798.86523
764.9321
781.7304
582.2019
773.16614
633.6009
836.07263
660.28436
791.0135
672.397
794.2207
725.2072
787.78705
696.1729
790.4462
712.74286
798.9607
658.58887
800.85724
702.4296
809.68024
604.38385
797.7996
629.5391
769.86346
609.3294
755.95245
548.8711
781.8096
706.76624
768.641
720.7137
769.3843
542.3312
771.105
732.4841
801.30646
667.39386
782.3083
663.36896
781.0351
617.22485
782.3598
710.58185
785.34143
694.71387
775.51666
500.7253
773.13
656.4944
782.9994
653.4169
782.0273
599.7809
764.7752
629.4701
785.3805
819.6346
771.167
703.80554
775.8679
762.2848
757.5077
520.957
750.6979
619.80835
771.08466
619.08923
769.9719
646.8245
786.86597
602.45404
741.99115
608.83405
781.28564


 40%|████      | 2/5 [00:25<00:41, 13.90s/it, mean_val_loss=25.4]

583.6518
746.9593
713.20465
770.14703
632.9477
743.07166
775.6168
748.4634
426.7404
777.08234
674.58215
748.5558
668.5632
744.8795
580.3534
739.11163
720.7561
759.55444
605.15155
766.0337
584.38354
763.63153
706.1939
716.1916
721.73047
745.9146
495.98846
755.89014
751.42975
766.2052
467.09277
786.51697
620.66547
754.21716
555.3419
763.0724
602.5069
788.2986
704.6636
781.8334
578.85846
788.84045
570.77325
794.7168
641.38715
789.9568
588.8081
790.57056
572.3375
778.9756
544.24945
753.77466
544.86316
777.48645
506.33383
767.4134
572.49817
755.29456
628.97345
781.25916
640.71747
825.74335
562.7727
772.4592
585.7395
778.5832
602.4987
799.50116
644.3079
808.814
640.44354
786.83636
594.4043
792.66473
638.35034
798.20465
702.21783
766.9191
497.46216
805.67255
565.43524
782.02704
554.136
793.6892
663.61005
797.85254
652.18915
792.48224
590.58484
779.9272
626.79
781.95416
565.0648
789.5943
660.8862
754.8753
517.7083
769.1004
713.2161
783.11346


 60%|██████    | 3/5 [00:35<00:25, 12.73s/it, mean_val_loss=24.7]

518.39056
771.947
696.30286
816.0959
737.1734
788.54755
668.9889
775.89545
486.5506
782.086
644.5273
785.6363
625.21027
765.9063
645.3838
769.59576
593.0075
747.276
496.42355
765.4325
566.0729
802.16223
823.1319
772.982
546.0357
747.8653
611.1655
763.0007
620.3582
772.3654
671.1666
740.14734
592.4747
766.9764
700.42114
785.41064
516.37286
760.657
529.06635
775.58704
545.32367
782.8907
452.9998
748.8415
548.9161
757.89185
606.78564
746.4153
798.86426
750.67145
580.97516
745.1661
509.9293
751.02167
691.6973
745.81226
610.6265
767.72144
524.3637
741.12915
634.1179
784.78125
551.6136
753.7084
493.03604
764.323
458.77853
767.80524
630.1818
778.92645
504.3121
777.20306
602.35815
762.2481
448.23032
771.28345
551.7349
756.18884
562.27106
739.7539
644.72766
763.5125
669.2682
777.8877
641.249
747.31934
592.63544
739.8306
509.36652
745.3142
605.5749
757.1082
430.57938
746.83044
569.8827
753.90845
620.484
784.2384
707.1104
767.3398


 80%|████████  | 4/5 [00:45<00:11, 11.92s/it, mean_val_loss=24.8]

665.9164
773.13025
445.7698
747.80023
398.1087
745.71826
531.338
749.4799
599.2278
798.8358
490.86
751.56177
631.84485
757.102
601.6336
795.5061
634.6445
790.40454
503.36353
752.13385
489.97385
768.47363
457.4237
748.05383
509.76685
759.63873
506.3738
761.54663
566.6033
762.2727
445.2157
764.42017
517.8434
768.8343
592.44366
768.8391
641.1883
751.9886
436.42877
766.93994
549.7879
786.8651
624.478
736.72784
635.78235
743.2137
488.17532
780.67413
680.3915
764.5177
652.6474
763.5239
547.15564
757.93164
498.92325
746.24866
537.89594
754.64746
417.29755
767.65814
790.4767
737.29694
564.2343
735.005
671.645
766.82825
524.9593
756.3949
618.4
759.83435
472.47626
762.1105
444.09708
771.48645
624.9315
777.1065
541.74194
758.7746
531.084
742.94696
552.7586
750.93036
662.6724
765.41144
547.3021
735.0179
517.7299
723.0262
678.0079
749.2058
697.46814
765.15533
496.5868
757.89246
624.3987
730.6144
525.2265
748.447
497.73618
758.82855


100%|██████████| 5/5 [00:55<00:00, 11.12s/it, mean_val_loss=23.9]
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:536: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  append_fn(tensor_proto, proto_values)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:536: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  append_fn(tensor_proto, proto_values)


loading_vars_from inf_ne_5_lr_1e-06_bs_1000_t_0.1/model.ckpt-250
INFO:tensorflow:Restoring parameters from inf_ne_5_lr_1e-06_bs_1000_t_0.1/model.ckpt-250
[[ 2.4813963e-03 -1.3762937e-01 -4.4337213e-02  8.7590748e-04]
 [-1.3763013e-01  5.4693237e+01 -5.3892055e+00  6.8815053e-03]
 [-4.4336736e-02 -5.3891783e+00  6.0750785e+00  2.2168406e-03]
 [ 8.7590748e-04  6.8806354e-03  2.2163633e-03  9.5620204e-04]]
